### PR TITLE
Product page logic

### PR DESCRIPTION
**Pull request by Mohammad-dn**

### CODE REVIEW

**Comment by mahdi-eth** [comment]
Hi, Mehdi has coded the footer.

**Comment by mahdi-eth** [comment]
Hey there, thanks for the pull request! Just wanted to kindly remind you to update your code by fetching and pulling from the main branch. Also, just a heads up, Mehdi has already implemented the footer. Thanks for your contributions!

**Review by mahdi-eth — APPROVED** [review]
Great job, Mohammad! Your changes have been approved and merged into the master branch. Thank you for your contribution to the project. Keep up the good work!

**Comment by Mohammad-dn** [comment]
@mahdi-eth Your words of encouragement are much appreciated, and I will do my best to continue contributing to the project's success. Please feel free to let me know if there is anything else I can do to support the project.

Thanks again for your support, and I look forward to working with you in the future.

Best regards,

Mohammad

**Pull request merged**
